### ISSUE TITLE
Question about the enumerate(val_loader)

### ISSUE THREAD

**Issue by theodoruszq** [XiaohangZhan/dist-framework#1]
Hi Xiaohang Zhan,

It is a wonderful framework for deep learning community. However I encounter a question about the speed is very slow when enumerate(val_loader).

https://github.com/XiaohangZhan/dist-framework/blob/b68828c149ef6adc79aabc1ef98b4e6e730fa844/trainer.py#L260

Have you ever encountered this problem? It waits at the _Multiprocessing Method (w.start() Line 722 in torch.utils.data.dataloader) for about 25 seconds for a process init. I don't know it is because the DistributeSampler or the PyTorch framework itself.

Thanks,
sydney0zq

**Comment by XiaohangZhan** [comment]
Did you solve it? This framework is mainly used by myself previously and has not been maintained for a long time.

**Comment by theodoruszq** [comment]
I have solved it. The framework still works well. This question is mainly because there exists one very huge attribute member (i.e. COCO annotation) that costs a lot of time to share among multiple processes. It has no problem in your framework, and the problem originates from pytorch multiprocessing.
